main: src/main.c src/lib/globals.c src/lib/menus.c src/lib/reservation.c
	gcc src/main.c src/lib/globals.c src/lib/menus.c src/lib/reservation.c -o build/main

clean:
	echo 100 > data/tickets/ticket_count.txt; echo 1 > data/tickets/seatno_count.txt;