main: src/main.c src/lib/globals.c src/lib/menus.c src/lib/reservation.c src/lib/getters.c
	gcc src/main.c src/lib/globals.c src/lib/menus.c src/lib/reservation.c src/lib/getters.c -o build/main

clean:
	echo 100 > build/data/tickets/ticket_count.txt; echo 1 > build/data/tickets/seatno_count.txt;